config:
  vendor_id: 1462
  product_id: 1563
  next_stage_hotkey: Super-F8  # remove if you don't want gdk keybinds
  next_profile_hotkey: Super-F7  # remove if you don't want gdk keybinds

profiles:
  - name: profile_1
    default: yes
    stages:
      - state: on
        brightness: 1
        colour: [255, 255, 255]

      - state: on
        brightness: 3
        colour: [255, 255, 255]

      - state: on
        brightness: 5
        colour: [255, 255, 255]

      - state: off

  - name: profile_2
    stages:
      - state: on
        brightness: 1
        colour: [255, 255, 0]

      - state: on
        brightness: 3
        colour: [255, 255, 0]

      - state: on
        brightness: 5
        colour: [255, 255, 0]

      - state: off