config:
  vendor_id: 1462
  product_id: 1563
  dbus_enabled: yes
  hotkeys_enabled: yes
  next_stage_hotkey: Super-F8  # remove if you don't want global gdk keybind for next_stage
  next_profile_hotkey: Super-F7  # remove if you don't want global gdk keybind for next_profile

profiles:
  - name: profile_1
    default: yes
    stages:
      - state: on
        brightness: 1
        colour: white

      - state: on
        brightness: 3
        colour: white

      - state: on
        brightness: 5
        colour: white

      - state: off

  - name: profile_2
    stages:
      - state: on
        brightness: 1
        colour: red

      - state: on
        brightness: 3
        colour: red

      - state: on
        brightness: 5
        colour: red

      - state: off